"""add_customer_surname_and_subject_to_appointments

Revision ID: 0cb0f0174540
Revises: 4f289823e20c
Create Date: 2026-02-28 13:17:00.373877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb0f0174540'
down_revision: Union[str, Sequence[str], None] = '4f289823e20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('customer_surname', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('subject', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'subject')
    op.drop_column('appointments', 'customer_surname')
    # ### end Alembic commands ###
