"""add_user_id_to_appointments

Revision ID: 433ed6ce919e
Revises: 087c488355cb
Create Date: 2026-02-28 22:11:25.655656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433ed6ce919e'
down_revision: Union[str, Sequence[str], None] = '087c488355cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
